package ru.detmir.sap.mapping.model;/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * ru.detmir.sap.model.cheque.AtolReportResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-15T05:59:41.749518627Z[GMT]")
public class AtolReportResponse {
  @SerializedName("callbackUrl")
  private String callbackUrl = null;

  @SerializedName("daemonCode")
  private String daemonCode = null;

  @SerializedName("deviceCode")
  private String deviceCode = null;

  @SerializedName("warnings")
  private String warnings = null;

  @SerializedName("externalId")
  private String externalId = null;

  @SerializedName("groupCode")
  private String groupCode = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("uuid")
  private String uuid = null;

  @SerializedName("payload")
  private AtolReportPayload payload = null;

  public AtolReportResponse callbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

   /**
   * Get callbackUrl
   * @return callbackUrl
  **/
  public String getCallbackUrl() {
    return callbackUrl;
  }

  public void setCallbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }

  public AtolReportResponse daemonCode(String daemonCode) {
    this.daemonCode = daemonCode;
    return this;
  }

   /**
   * Get daemonCode
   * @return daemonCode
  **/
  public String getDaemonCode() {
    return daemonCode;
  }

  public void setDaemonCode(String daemonCode) {
    this.daemonCode = daemonCode;
  }

  public AtolReportResponse deviceCode(String deviceCode) {
    this.deviceCode = deviceCode;
    return this;
  }

   /**
   * Get deviceCode
   * @return deviceCode
  **/
  public String getDeviceCode() {
    return deviceCode;
  }

  public void setDeviceCode(String deviceCode) {
    this.deviceCode = deviceCode;
  }

  public AtolReportResponse warnings(String warnings) {
    this.warnings = warnings;
    return this;
  }

   /**
   * Get warnings
   * @return warnings
  **/
  public String getWarnings() {
    return warnings;
  }

  public void setWarnings(String warnings) {
    this.warnings = warnings;
  }

  public AtolReportResponse externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public AtolReportResponse groupCode(String groupCode) {
    this.groupCode = groupCode;
    return this;
  }

   /**
   * Get groupCode
   * @return groupCode
  **/
  public String getGroupCode() {
    return groupCode;
  }

  public void setGroupCode(String groupCode) {
    this.groupCode = groupCode;
  }

  public AtolReportResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public AtolReportResponse uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public AtolReportResponse payload(AtolReportPayload payload) {
    this.payload = payload;
    return this;
  }

   /**
   * Get payload
   * @return payload
  **/
  public AtolReportPayload getPayload() {
    return payload;
  }

  public void setPayload(AtolReportPayload payload) {
    this.payload = payload;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AtolReportResponse atolReportResponse = (AtolReportResponse) o;
    return Objects.equals(this.callbackUrl, atolReportResponse.callbackUrl) &&
        Objects.equals(this.daemonCode, atolReportResponse.daemonCode) &&
        Objects.equals(this.deviceCode, atolReportResponse.deviceCode) &&
        Objects.equals(this.warnings, atolReportResponse.warnings) &&
        Objects.equals(this.externalId, atolReportResponse.externalId) &&
        Objects.equals(this.groupCode, atolReportResponse.groupCode) &&
        Objects.equals(this.status, atolReportResponse.status) &&
        Objects.equals(this.uuid, atolReportResponse.uuid) &&
        Objects.equals(this.payload, atolReportResponse.payload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callbackUrl, daemonCode, deviceCode, warnings, externalId, groupCode, status, uuid, payload);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ru.detmir.sap.model.cheque.AtolReportResponse {\n");
    
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    daemonCode: ").append(toIndentedString(daemonCode)).append("\n");
    sb.append("    deviceCode: ").append(toIndentedString(deviceCode)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    groupCode: ").append(toIndentedString(groupCode)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
