package ru.detmir.sap.mapping.model;

/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.adapters.XmlAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * ru.detmir.sap.model.cheque.ChequeDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-15T05:59:41.749518627Z[GMT]")
@XmlRootElement(namespace = "urn:DetMir.ru:Hybris:Finance", name = "SalesEmailCheckRequest")
public class ChequeDto {

    private Integer id = null;


    private String externalId = null;


    private String retailTransactionNumber = null;


    private String retailCalendarDay = null;


    private String orderGuid = null;


    private String orderCode = null;


    private String groupCode = null;


    private String groupGuid = null;


    private BigDecimal totalAmount = null;


    private BigDecimal totalDiscount = null;


    private Long createdTs = null;

    /**
     * Gets or Sets type
     */
    @XmlJavaTypeAdapter(TypeEnum.XMLAdapter.class)
    public enum TypeEnum {
        SALE("sale"),
        REFUND("refund");

        private String value;

        TypeEnum(String value) {
            this.value = value;
        }
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
        public static TypeEnum fromValue(String input) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(input)) {
                    return b;
                }
            }
            return null;
        }


        public static class XMLAdapter extends XmlAdapter<String, TypeEnum> {

            @Override
            public TypeEnum unmarshal(String v) throws Exception {
                return TypeEnum.fromValue(v);
            }

            @Override
            public String marshal(TypeEnum v) throws Exception {
                return v.getValue();
            }
        }
    }
    private TypeEnum type = null;


    private AtolReportResponse atolData = null;


    private String description = null;


    private String url = null;


    private String userEmail = null;


    private String userName = null;


    private String userPhone = null;


    private Long createdTsSource = null;


    private String msgId = null;


    private SourceRetailChequeDto sourceRetailCheque = null;

    /**
     * Gets or Sets channel
     */
    @XmlJavaTypeAdapter(ChannelEnum.XMLAdapter.class)
    public enum ChannelEnum {
        ONLINE("online"),
        OFFLINE("offline");

        private String value;

        ChannelEnum(String value) {
            this.value = value;
        }
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
        public static ChannelEnum fromValue(String input) {
            for (ChannelEnum b : ChannelEnum.values()) {
                if (b.value.equals(input)) {
                    return b;
                }
            }
            return null;
        }

        public static class XMLAdapter extends XmlAdapter<String, ChannelEnum> {

            @Override
            public ChannelEnum unmarshal(String v) throws Exception {
                return ChannelEnum.fromValue(v);
            }

            @Override
            public String marshal(ChannelEnum v) throws Exception {
                return v.getValue();
            }
        }
    }
    private ChannelEnum channel = null;


    private List<ItemDto> items = null;


    private Boolean prepaid = null;


    private LoyaltyTransactionDto loyalty = null;


    private String cashier = null;


    private String posId = null;


    private String address = null;


    private String placeOfSettlement = null;

    /**
     * Gets or Sets chain
     */
    @XmlJavaTypeAdapter(ChainEnum.XMLAdapter.class)
    public enum ChainEnum {
        ZOOZAVR("zoozavr"),
        DETMIR("detmir");

        private String value;

        ChainEnum(String value) {
            this.value = value;
        }
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
        public static ChainEnum fromValue(String input) {
            for (ChainEnum b : ChainEnum.values()) {
                if (b.value.equals(input)) {
                    return b;
                }
            }
            return null;
        }

        public static class XMLAdapter extends XmlAdapter<String, ChainEnum> {

            @Override
            public ChainEnum unmarshal(String v) throws Exception {
                return ChainEnum.fromValue(v);
            }

            @Override
            public String marshal(ChainEnum v) throws Exception {
                return v.getValue();
            }
        }
    }
    private ChainEnum chain = null;


    private String loyaltyPromoText = null;


    private String promoText = null;


    private String giftCard = null;


    private Long giftCardTs = null;


    private BigDecimal giftCardAmount = null;


    private String bonusCard = null;


    private BigDecimal redeemed = null;


    private BigDecimal awarded = null;


    private BigDecimal loyaltyBalance = null;


    private BigDecimal loyaltyActivePoints = null;


    private BigDecimal loyaltyInactivePoints = null;


    private Map<String, BigDecimal> ndsMap = null;


    private Boolean sent = null;


    private Boolean mustBeSent = null;

    /**
     * Gets or Sets paymentMethod
     */
    @XmlJavaTypeAdapter(PaymentMethodEnum.XMLAdapter.class)
    public enum PaymentMethodEnum {
        CARD("card"),
        CASH("cash"),
        PAYPAL("paypal"),
        LOYALTY("loyalty"),
        GIFT("gift"),
        QUICKPAY("quickpay"),
        APPLEPAY("applepay"),
        GOOGLEPAY("googlepay"),
        SAMSUNGPAY("samsungpay"),
        GIFTCARD("giftcard"),
        MOKKA("mokka"),
        DOLYAME("dolyame");

        private String value;

        PaymentMethodEnum(String value) {
            this.value = value;
        }
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
        public static PaymentMethodEnum fromValue(String input) {
            for (PaymentMethodEnum b : PaymentMethodEnum.values()) {
                if (b.value.equals(input)) {
                    return b;
                }
            }
            return null;
        }
        public static class XMLAdapter extends XmlAdapter<String, PaymentMethodEnum> {

            @Override
            public PaymentMethodEnum unmarshal(String v) throws Exception {
                return PaymentMethodEnum.fromValue(v);
            }

            @Override
            public String marshal(PaymentMethodEnum v) throws Exception {
                return v.getValue();
            }
        }
    }
    private PaymentMethodEnum paymentMethod = null;


    private BigDecimal cardAmount = null;


    private BigDecimal cashAmount = null;


    private List<GiftCardTransactionDto> giftCardDetails = null;


    private Map<String, String> properties = null;


    private Boolean groupPublicId = null;

    public ChequeDto id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     **/
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public ChequeDto externalId(String externalId) {
        this.externalId = externalId;
        return this;
    }

    /**
     * Get externalId
     * @return externalId
     **/
    public String getExternalId() {
        return externalId;
    }

    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }


    public ChequeDto retailTransactionNumber(String retailTransactionNumber) {
        this.retailTransactionNumber = retailTransactionNumber;
        return this;
    }


    public ChequeDto retailCalendarDay(String retailCalendarDay) {
        this.retailCalendarDay = retailCalendarDay;
        return this;
    }

    public String getRetailCalendarDay() {
        return retailCalendarDay;
    }

    public void setRetailCalendarDay(String retailCalendarDay) {
        this.retailCalendarDay = retailCalendarDay;
    }

    public Boolean getMustBeSent() {
        return mustBeSent;
    }

    public String getRetailTransactionNumber() {
        return retailTransactionNumber;
    }

    public void setRetailTransactionNumber(String retailTransactionNumber) {
        this.retailTransactionNumber = retailTransactionNumber;
    }

    public Boolean getPrepaid() {
        return prepaid;
    }

    public Boolean getSent() {
        return sent;
    }

    public Boolean getGroupPublicId() {
        return groupPublicId;
    }

    public ChequeDto orderGuid(String orderGuid) {
        this.orderGuid = orderGuid;
        return this;
    }

    /**
     * Get orderGuid
     * @return orderGuid
     **/
    public String getOrderGuid() {
        return orderGuid;
    }

    public void setOrderGuid(String orderGuid) {
        this.orderGuid = orderGuid;
    }

    public ChequeDto orderCode(String orderCode) {
        this.orderCode = orderCode;
        return this;
    }

    /**
     * Get orderCode
     * @return orderCode
     **/
    public String getOrderCode() {
        return orderCode;
    }

    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    public ChequeDto groupCode(String groupCode) {
        this.groupCode = groupCode;
        return this;
    }

    /**
     * Get groupCode
     * @return groupCode
     **/
    public String getGroupCode() {
        return groupCode;
    }

    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    public ChequeDto groupGuid(String groupGuid) {
        this.groupGuid = groupGuid;
        return this;
    }

    /**
     * Get groupGuid
     * @return groupGuid
     **/
    public String getGroupGuid() {
        return groupGuid;
    }

    public void setGroupGuid(String groupGuid) {
        this.groupGuid = groupGuid;
    }

    public ChequeDto totalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
        return this;
    }

    /**
     * Get totalAmount
     * @return totalAmount
     **/
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public ChequeDto totalDiscount(BigDecimal totalDiscount) {
        this.totalDiscount = totalDiscount;
        return this;
    }

    /**
     * Get totalDiscount
     * @return totalDiscount
     **/
    public BigDecimal getTotalDiscount() {
        return totalDiscount;
    }

    public void setTotalDiscount(BigDecimal totalDiscount) {
        this.totalDiscount = totalDiscount;
    }

    public ChequeDto createdTs(Long createdTs) {
        this.createdTs = createdTs;
        return this;
    }

    /**
     * Get createdTs
     * @return createdTs
     **/
    public Long getCreatedTs() {
        return createdTs;
    }

    public void setCreatedTs(Long createdTs) {
        this.createdTs = createdTs;
    }

    public ChequeDto type(TypeEnum type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * @return type
     **/
    public TypeEnum getType() {
        return type;
    }

    public void setType(TypeEnum type) {
        this.type = type;
    }

    public ChequeDto atolData(AtolReportResponse atolData) {
        this.atolData = atolData;
        return this;
    }

    /**
     * Get atolData
     * @return atolData
     **/
    public AtolReportResponse getAtolData() {
        return atolData;
    }

    public void setAtolData(AtolReportResponse atolData) {
        this.atolData = atolData;
    }

    public ChequeDto description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     * @return description
     **/
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ChequeDto url(String url) {
        this.url = url;
        return this;
    }

    /**
     * Get url
     * @return url
     **/
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public ChequeDto userEmail(String userEmail) {
        this.userEmail = userEmail;
        return this;
    }

    /**
     * Get userEmail
     * @return userEmail
     **/
    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public ChequeDto userName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Get userName
     * @return userName
     **/
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public ChequeDto userPhone(String userPhone) {
        this.userPhone = userPhone;
        return this;
    }

    /**
     * Get userPhone
     * @return userPhone
     **/
    public String getUserPhone() {
        return userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    public ChequeDto createdTsSource(Long createdTsSource) {
        this.createdTsSource = createdTsSource;
        return this;
    }

    public ChequeDto msgId(String msgId) {
        this.msgId = msgId;
        return this;
    }

    public String getMsgId() {
        return msgId;
    }

    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    /**
     * Get createdTsSource
     * @return createdTsSource
     **/
    public Long getCreatedTsSource() {
        return createdTsSource;
    }

    public void setCreatedTsSource(Long createdTsSource) {
        this.createdTsSource = createdTsSource;
    }

    public ChequeDto channel(ChannelEnum channel) {
        this.channel = channel;
        return this;
    }

    /**
     * Get channel
     * @return channel
     **/
    public ChannelEnum getChannel() {
        return channel;
    }

    public void setChannel(ChannelEnum channel) {
        this.channel = channel;
    }

    public ChequeDto sourceRetailCheque(SourceRetailChequeDto sourceRetailCheque) {
        this.sourceRetailCheque = sourceRetailCheque;
        return this;
    }

    public SourceRetailChequeDto getSourceRetailCheque() {
        return sourceRetailCheque;
    }

    public void setSourceRetailCheque(SourceRetailChequeDto sourceRetailCheque) {
        this.sourceRetailCheque = sourceRetailCheque;
    }

    public ChequeDto items(List<ItemDto> items) {
        this.items = items;
        return this;
    }

    public ChequeDto addItemsItem(ItemDto itemsItem) {
        if (this.items == null) {
            this.items = new ArrayList<ItemDto>();
        }
        this.items.add(itemsItem);
        return this;
    }

    /**
     * Get items
     * @return items
     **/
    public List<ItemDto> getItems() {
        return items;
    }

    public void setItems(List<ItemDto> items) {
        this.items = items;
    }

    public ChequeDto prepaid(Boolean prepaid) {
        this.prepaid = prepaid;
        return this;
    }

    /**
     * Get prepaid
     * @return prepaid
     **/
    public Boolean isPrepaid() {
        return prepaid;
    }

    public void setPrepaid(Boolean prepaid) {
        this.prepaid = prepaid;
    }

    public ChequeDto loyalty(LoyaltyTransactionDto loyalty) {
        this.loyalty = loyalty;
        return this;
    }

    /**
     * Get loyalty
     * @return loyalty
     **/
    public LoyaltyTransactionDto getLoyalty() {
        return loyalty;
    }

    public void setLoyalty(LoyaltyTransactionDto loyalty) {
        this.loyalty = loyalty;
    }

    public ChequeDto cashier(String cashier) {
        this.cashier = cashier;
        return this;
    }

    /**
     * Get cashier
     * @return cashier
     **/
    public String getCashier() {
        return cashier;
    }

    public void setCashier(String cashier) {
        this.cashier = cashier;
    }

    public ChequeDto posId(String posId) {
        this.posId = posId;
        return this;
    }

    /**
     * Get posId
     * @return posId
     **/
    public String getPosId() {
        return posId;
    }

    public void setPosId(String posId) {
        this.posId = posId;
    }

    public ChequeDto address(String address) {
        this.address = address;
        return this;
    }

    /**
     * Get address
     * @return address
     **/
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public ChequeDto placeOfSettlement(String placeOfSettlement) {
        this.placeOfSettlement = placeOfSettlement;
        return this;
    }

    /**
     * Get placeOfSettlement
     * @return placeOfSettlement
     **/
    public String getPlaceOfSettlement() {
        return placeOfSettlement;
    }

    public void setPlaceOfSettlement(String placeOfSettlement) {
        this.placeOfSettlement = placeOfSettlement;
    }

    public ChequeDto chain(ChainEnum chain) {
        this.chain = chain;
        return this;
    }

    /**
     * Get chain
     * @return chain
     **/
    public ChainEnum getChain() {
        return chain;
    }

    public void setChain(ChainEnum chain) {
        this.chain = chain;
    }

    public ChequeDto loyaltyPromoText(String loyaltyPromoText) {
        this.loyaltyPromoText = loyaltyPromoText;
        return this;
    }

    /**
     * Get loyaltyPromoText
     * @return loyaltyPromoText
     **/
    public String getLoyaltyPromoText() {
        return loyaltyPromoText;
    }

    public void setLoyaltyPromoText(String loyaltyPromoText) {
        this.loyaltyPromoText = loyaltyPromoText;
    }

    public ChequeDto promoText(String promoText) {
        this.promoText = promoText;
        return this;
    }

    /**
     * Get promoText
     * @return promoText
     **/
    public String getPromoText() {
        return promoText;
    }

    public void setPromoText(String promoText) {
        this.promoText = promoText;
    }

    public ChequeDto giftCard(String giftCard) {
        this.giftCard = giftCard;
        return this;
    }

    /**
     * Get giftCard
     * @return giftCard
     **/
    public String getGiftCard() {
        return giftCard;
    }

    public void setGiftCard(String giftCard) {
        this.giftCard = giftCard;
    }

    public ChequeDto giftCardTs(Long giftCardTs) {
        this.giftCardTs = giftCardTs;
        return this;
    }

    /**
     * Get giftCardTs
     * @return giftCardTs
     **/
    public Long getGiftCardTs() {
        return giftCardTs;
    }

    public void setGiftCardTs(Long giftCardTs) {
        this.giftCardTs = giftCardTs;
    }

    public ChequeDto giftCardAmount(BigDecimal giftCardAmount) {
        this.giftCardAmount = giftCardAmount;
        return this;
    }

    /**
     * Get giftCardAmount
     * @return giftCardAmount
     **/
    public BigDecimal getGiftCardAmount() {
        return giftCardAmount;
    }

    public void setGiftCardAmount(BigDecimal giftCardAmount) {
        this.giftCardAmount = giftCardAmount;
    }

    public ChequeDto bonusCard(String bonusCard) {
        this.bonusCard = bonusCard;
        return this;
    }

    /**
     * Get bonusCard
     * @return bonusCard
     **/
    public String getBonusCard() {
        return bonusCard;
    }

    public void setBonusCard(String bonusCard) {
        this.bonusCard = bonusCard;
    }

    public ChequeDto redeemed(BigDecimal redeemed) {
        this.redeemed = redeemed;
        return this;
    }

    /**
     * Get redeemed
     * @return redeemed
     **/
    public BigDecimal getRedeemed() {
        return redeemed;
    }

    public void setRedeemed(BigDecimal redeemed) {
        this.redeemed = redeemed;
    }

    public ChequeDto awarded(BigDecimal awarded) {
        this.awarded = awarded;
        return this;
    }

    /**
     * Get awarded
     * @return awarded
     **/
    public BigDecimal getAwarded() {
        return awarded;
    }

    public void setAwarded(BigDecimal awarded) {
        this.awarded = awarded;
    }

    public ChequeDto loyaltyBalance(BigDecimal loyaltyBalance) {
        this.loyaltyBalance = loyaltyBalance;
        return this;
    }

    /**
     * Get loyaltyBalance
     * @return loyaltyBalance
     **/
    public BigDecimal getLoyaltyBalance() {
        return loyaltyBalance;
    }

    public void setLoyaltyBalance(BigDecimal loyaltyBalance) {
        this.loyaltyBalance = loyaltyBalance;
    }

    public ChequeDto loyaltyActivePoints(BigDecimal loyaltyActivePoints) {
        this.loyaltyActivePoints = loyaltyActivePoints;
        return this;
    }

    /**
     * Get loyaltyActivePoints
     * @return loyaltyActivePoints
     **/
    public BigDecimal getLoyaltyActivePoints() {
        return loyaltyActivePoints;
    }

    public void setLoyaltyActivePoints(BigDecimal loyaltyActivePoints) {
        this.loyaltyActivePoints = loyaltyActivePoints;
    }

    public ChequeDto loyaltyInactivePoints(BigDecimal loyaltyInactivePoints) {
        this.loyaltyInactivePoints = loyaltyInactivePoints;
        return this;
    }

    /**
     * Get loyaltyInactivePoints
     * @return loyaltyInactivePoints
     **/
    public BigDecimal getLoyaltyInactivePoints() {
        return loyaltyInactivePoints;
    }

    public void setLoyaltyInactivePoints(BigDecimal loyaltyInactivePoints) {
        this.loyaltyInactivePoints = loyaltyInactivePoints;
    }

    public ChequeDto ndsMap(Map<String, BigDecimal> ndsMap) {
        this.ndsMap = ndsMap;
        return this;
    }

    public ChequeDto putNdsMapItem(String key, BigDecimal ndsMapItem) {
        if (this.ndsMap == null) {
            this.ndsMap = new HashMap<String, BigDecimal>();
        }
        this.ndsMap.put(key, ndsMapItem);
        return this;
    }

    /**
     * Get ndsMap
     * @return ndsMap
     **/
    public Map<String, BigDecimal> getNdsMap() {
        return ndsMap;
    }

    public void setNdsMap(Map<String, BigDecimal> ndsMap) {
        this.ndsMap = ndsMap;
    }

    public ChequeDto sent(Boolean sent) {
        this.sent = sent;
        return this;
    }

    /**
     * Get sent
     * @return sent
     **/
    public Boolean isSent() {
        return sent;
    }

    public void setSent(Boolean sent) {
        this.sent = sent;
    }

    public ChequeDto mustBeSent(Boolean mustBeSent) {
        this.mustBeSent = mustBeSent;
        return this;
    }

    /**
     * Get mustBeSent
     * @return mustBeSent
     **/
    public Boolean isMustBeSent() {
        return mustBeSent;
    }

    public void setMustBeSent(Boolean mustBeSent) {
        this.mustBeSent = mustBeSent;
    }

    public ChequeDto paymentMethod(PaymentMethodEnum paymentMethod) {
        this.paymentMethod = paymentMethod;
        return this;
    }

    /**
     * Get paymentMethod
     * @return paymentMethod
     **/
    public PaymentMethodEnum getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethodEnum paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public ChequeDto cardAmount(BigDecimal cardAmount) {
        this.cardAmount = cardAmount;
        return this;
    }

    /**
     * Get cardAmount
     * @return cardAmount
     **/
    public BigDecimal getCardAmount() {
        return cardAmount;
    }

    public void setCardAmount(BigDecimal cardAmount) {
        this.cardAmount = cardAmount;
    }

    public ChequeDto cashAmount(BigDecimal cashAmount) {
        this.cashAmount = cashAmount;
        return this;
    }

    /**
     * Get cashAmount
     * @return cashAmount
     **/
    public BigDecimal getCashAmount() {
        return cashAmount;
    }

    public void setCashAmount(BigDecimal cashAmount) {
        this.cashAmount = cashAmount;
    }

    public ChequeDto giftCardDetails(List<GiftCardTransactionDto> giftCardDetails) {
        this.giftCardDetails = giftCardDetails;
        return this;
    }

    public ChequeDto addGiftCardDetailsItem(GiftCardTransactionDto giftCardDetailsItem) {
        if (this.giftCardDetails == null) {
            this.giftCardDetails = new ArrayList<GiftCardTransactionDto>();
        }
        this.giftCardDetails.add(giftCardDetailsItem);
        return this;
    }

    /**
     * Get giftCardDetails
     * @return giftCardDetails
     **/
    public List<GiftCardTransactionDto> getGiftCardDetails() {
        return giftCardDetails;
    }

    public void setGiftCardDetails(List<GiftCardTransactionDto> giftCardDetails) {
        this.giftCardDetails = giftCardDetails;
    }

    public ChequeDto properties(Map<String, String> properties) {
        this.properties = properties;
        return this;
    }

    public ChequeDto putPropertiesItem(String key, String propertiesItem) {
        if (this.properties == null) {
            this.properties = new HashMap<String, String>();
        }
        this.properties.put(key, propertiesItem);
        return this;
    }

    /**
     * Get properties
     * @return properties
     **/
    public Map<String, String> getProperties() {
        return properties;
    }

    public void setProperties(Map<String, String> properties) {
        this.properties = properties;
    }

    public ChequeDto groupPublicId(Boolean groupPublicId) {
        this.groupPublicId = groupPublicId;
        return this;
    }

    /**
     * Get groupPublicId
     * @return groupPublicId
     **/
    public Boolean isGroupPublicId() {
        return groupPublicId;
    }

    public void setGroupPublicId(Boolean groupPublicId) {
        this.groupPublicId = groupPublicId;
    }


    @Override
    public String toString() {
        return "ChequeDto{" +
               "id=" + id +
               ", externalId='" + externalId + '\'' +
               ", retailTransactionNumber='" + retailTransactionNumber + '\'' +
               ", retailCalendarDay='" + retailCalendarDay + '\'' +
               ", orderGuid='" + orderGuid + '\'' +
               ", orderCode='" + orderCode + '\'' +
               ", groupCode='" + groupCode + '\'' +
               ", groupGuid='" + groupGuid + '\'' +
               ", totalAmount=" + totalAmount +
               ", totalDiscount=" + totalDiscount +
               ", createdTs=" + createdTs +
               ", type=" + type +
               ", atolData=" + atolData +
               ", description='" + description + '\'' +
               ", url='" + url + '\'' +
               ", userEmail='" + userEmail + '\'' +
               ", userName='" + userName + '\'' +
               ", userPhone='" + userPhone + '\'' +
               ", createdTsSource=" + createdTsSource +
               ", msgId='" + msgId + '\'' +
               ", sourceRetailCheque=" + sourceRetailCheque +
               ", channel=" + channel +
               ", items=" + items +
               ", prepaid=" + prepaid +
               ", loyalty=" + loyalty +
               ", cashier='" + cashier + '\'' +
               ", posId='" + posId + '\'' +
               ", address='" + address + '\'' +
               ", placeOfSettlement='" + placeOfSettlement + '\'' +
               ", chain=" + chain +
               ", loyaltyPromoText='" + loyaltyPromoText + '\'' +
               ", promoText='" + promoText + '\'' +
               ", giftCard='" + giftCard + '\'' +
               ", giftCardTs=" + giftCardTs +
               ", giftCardAmount=" + giftCardAmount +
               ", bonusCard='" + bonusCard + '\'' +
               ", redeemed=" + redeemed +
               ", awarded=" + awarded +
               ", loyaltyBalance=" + loyaltyBalance +
               ", loyaltyActivePoints=" + loyaltyActivePoints +
               ", loyaltyInactivePoints=" + loyaltyInactivePoints +
               ", ndsMap=" + ndsMap +
               ", sent=" + sent +
               ", mustBeSent=" + mustBeSent +
               ", paymentMethod=" + paymentMethod +
               ", cardAmount=" + cardAmount +
               ", cashAmount=" + cashAmount +
               ", giftCardDetails=" + giftCardDetails +
               ", properties=" + properties +
               ", groupPublicId=" + groupPublicId +
               '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ChequeDto chequeDto = (ChequeDto) o;

        if (id != null ? !id.equals(chequeDto.id) : chequeDto.id != null) return false;
        if (externalId != null ? !externalId.equals(chequeDto.externalId) : chequeDto.externalId != null) return false;
        if (retailTransactionNumber != null ? !retailTransactionNumber.equals(chequeDto.retailTransactionNumber) : chequeDto.retailTransactionNumber != null)
            return false;
        if (retailCalendarDay != null ? !retailCalendarDay.equals(chequeDto.retailCalendarDay) : chequeDto.retailCalendarDay != null)
            return false;
        if (orderGuid != null ? !orderGuid.equals(chequeDto.orderGuid) : chequeDto.orderGuid != null) return false;
        if (orderCode != null ? !orderCode.equals(chequeDto.orderCode) : chequeDto.orderCode != null) return false;
        if (groupCode != null ? !groupCode.equals(chequeDto.groupCode) : chequeDto.groupCode != null) return false;
        if (groupGuid != null ? !groupGuid.equals(chequeDto.groupGuid) : chequeDto.groupGuid != null) return false;
        if (totalAmount != null ? !totalAmount.equals(chequeDto.totalAmount) : chequeDto.totalAmount != null)
            return false;
        if (totalDiscount != null ? !totalDiscount.equals(chequeDto.totalDiscount) : chequeDto.totalDiscount != null)
            return false;
        if (createdTs != null ? !createdTs.equals(chequeDto.createdTs) : chequeDto.createdTs != null) return false;
        if (type != chequeDto.type) return false;
        if (atolData != null ? !atolData.equals(chequeDto.atolData) : chequeDto.atolData != null) return false;
        if (description != null ? !description.equals(chequeDto.description) : chequeDto.description != null)
            return false;
        if (url != null ? !url.equals(chequeDto.url) : chequeDto.url != null) return false;
        if (userEmail != null ? !userEmail.equals(chequeDto.userEmail) : chequeDto.userEmail != null) return false;
        if (userName != null ? !userName.equals(chequeDto.userName) : chequeDto.userName != null) return false;
        if (userPhone != null ? !userPhone.equals(chequeDto.userPhone) : chequeDto.userPhone != null) return false;
        if (createdTsSource != null ? !createdTsSource.equals(chequeDto.createdTsSource) : chequeDto.createdTsSource != null)
            return false;
        if (msgId != null ? !msgId.equals(chequeDto.msgId) : chequeDto.msgId != null) return false;
        if (sourceRetailCheque != null ? !sourceRetailCheque.equals(chequeDto.sourceRetailCheque) : chequeDto.sourceRetailCheque != null)
            return false;
        if (channel != chequeDto.channel) return false;
        if (items != null ? !items.equals(chequeDto.items) : chequeDto.items != null) return false;
        if (prepaid != null ? !prepaid.equals(chequeDto.prepaid) : chequeDto.prepaid != null) return false;
        if (loyalty != null ? !loyalty.equals(chequeDto.loyalty) : chequeDto.loyalty != null) return false;
        if (cashier != null ? !cashier.equals(chequeDto.cashier) : chequeDto.cashier != null) return false;
        if (posId != null ? !posId.equals(chequeDto.posId) : chequeDto.posId != null) return false;
        if (address != null ? !address.equals(chequeDto.address) : chequeDto.address != null) return false;
        if (placeOfSettlement != null ? !placeOfSettlement.equals(chequeDto.placeOfSettlement) : chequeDto.placeOfSettlement != null)
            return false;
        if (chain != chequeDto.chain) return false;
        if (loyaltyPromoText != null ? !loyaltyPromoText.equals(chequeDto.loyaltyPromoText) : chequeDto.loyaltyPromoText != null)
            return false;
        if (promoText != null ? !promoText.equals(chequeDto.promoText) : chequeDto.promoText != null) return false;
        if (giftCard != null ? !giftCard.equals(chequeDto.giftCard) : chequeDto.giftCard != null) return false;
        if (giftCardTs != null ? !giftCardTs.equals(chequeDto.giftCardTs) : chequeDto.giftCardTs != null) return false;
        if (giftCardAmount != null ? !giftCardAmount.equals(chequeDto.giftCardAmount) : chequeDto.giftCardAmount != null)
            return false;
        if (bonusCard != null ? !bonusCard.equals(chequeDto.bonusCard) : chequeDto.bonusCard != null) return false;
        if (redeemed != null ? !redeemed.equals(chequeDto.redeemed) : chequeDto.redeemed != null) return false;
        if (awarded != null ? !awarded.equals(chequeDto.awarded) : chequeDto.awarded != null) return false;
        if (loyaltyBalance != null ? !loyaltyBalance.equals(chequeDto.loyaltyBalance) : chequeDto.loyaltyBalance != null)
            return false;
        if (loyaltyActivePoints != null ? !loyaltyActivePoints.equals(chequeDto.loyaltyActivePoints) : chequeDto.loyaltyActivePoints != null)
            return false;
        if (loyaltyInactivePoints != null ? !loyaltyInactivePoints.equals(chequeDto.loyaltyInactivePoints) : chequeDto.loyaltyInactivePoints != null)
            return false;
        if (ndsMap != null ? !ndsMap.equals(chequeDto.ndsMap) : chequeDto.ndsMap != null) return false;
        if (sent != null ? !sent.equals(chequeDto.sent) : chequeDto.sent != null) return false;
        if (mustBeSent != null ? !mustBeSent.equals(chequeDto.mustBeSent) : chequeDto.mustBeSent != null) return false;
        if (paymentMethod != chequeDto.paymentMethod) return false;
        if (cardAmount != null ? !cardAmount.equals(chequeDto.cardAmount) : chequeDto.cardAmount != null) return false;
        if (cashAmount != null ? !cashAmount.equals(chequeDto.cashAmount) : chequeDto.cashAmount != null) return false;
        if (giftCardDetails != null ? !giftCardDetails.equals(chequeDto.giftCardDetails) : chequeDto.giftCardDetails != null)
            return false;
        if (properties != null ? !properties.equals(chequeDto.properties) : chequeDto.properties != null) return false;
        if (groupPublicId != null ? !groupPublicId.equals(chequeDto.groupPublicId) : chequeDto.groupPublicId != null)
            return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (externalId != null ? externalId.hashCode() : 0);
        result = 31 * result + (retailTransactionNumber != null ? retailTransactionNumber.hashCode() : 0);
        result = 31 * result + (retailCalendarDay != null ? retailCalendarDay.hashCode() : 0);
        result = 31 * result + (orderGuid != null ? orderGuid.hashCode() : 0);
        result = 31 * result + (orderCode != null ? orderCode.hashCode() : 0);
        result = 31 * result + (groupCode != null ? groupCode.hashCode() : 0);
        result = 31 * result + (groupGuid != null ? groupGuid.hashCode() : 0);
        result = 31 * result + (totalAmount != null ? totalAmount.hashCode() : 0);
        result = 31 * result + (totalDiscount != null ? totalDiscount.hashCode() : 0);
        result = 31 * result + (createdTs != null ? createdTs.hashCode() : 0);
        result = 31 * result + (type != null ? type.hashCode() : 0);
        result = 31 * result + (atolData != null ? atolData.hashCode() : 0);
        result = 31 * result + (description != null ? description.hashCode() : 0);
        result = 31 * result + (url != null ? url.hashCode() : 0);
        result = 31 * result + (userEmail != null ? userEmail.hashCode() : 0);
        result = 31 * result + (userName != null ? userName.hashCode() : 0);
        result = 31 * result + (userPhone != null ? userPhone.hashCode() : 0);
        result = 31 * result + (createdTsSource != null ? createdTsSource.hashCode() : 0);
        result = 31 * result + (msgId != null ? msgId.hashCode() : 0);
        result = 31 * result + (sourceRetailCheque != null ? sourceRetailCheque.hashCode() : 0);
        result = 31 * result + (channel != null ? channel.hashCode() : 0);
        result = 31 * result + (items != null ? items.hashCode() : 0);
        result = 31 * result + (prepaid != null ? prepaid.hashCode() : 0);
        result = 31 * result + (loyalty != null ? loyalty.hashCode() : 0);
        result = 31 * result + (cashier != null ? cashier.hashCode() : 0);
        result = 31 * result + (posId != null ? posId.hashCode() : 0);
        result = 31 * result + (address != null ? address.hashCode() : 0);
        result = 31 * result + (placeOfSettlement != null ? placeOfSettlement.hashCode() : 0);
        result = 31 * result + (chain != null ? chain.hashCode() : 0);
        result = 31 * result + (loyaltyPromoText != null ? loyaltyPromoText.hashCode() : 0);
        result = 31 * result + (promoText != null ? promoText.hashCode() : 0);
        result = 31 * result + (giftCard != null ? giftCard.hashCode() : 0);
        result = 31 * result + (giftCardTs != null ? giftCardTs.hashCode() : 0);
        result = 31 * result + (giftCardAmount != null ? giftCardAmount.hashCode() : 0);
        result = 31 * result + (bonusCard != null ? bonusCard.hashCode() : 0);
        result = 31 * result + (redeemed != null ? redeemed.hashCode() : 0);
        result = 31 * result + (awarded != null ? awarded.hashCode() : 0);
        result = 31 * result + (loyaltyBalance != null ? loyaltyBalance.hashCode() : 0);
        result = 31 * result + (loyaltyActivePoints != null ? loyaltyActivePoints.hashCode() : 0);
        result = 31 * result + (loyaltyInactivePoints != null ? loyaltyInactivePoints.hashCode() : 0);
        result = 31 * result + (ndsMap != null ? ndsMap.hashCode() : 0);
        result = 31 * result + (sent != null ? sent.hashCode() : 0);
        result = 31 * result + (mustBeSent != null ? mustBeSent.hashCode() : 0);
        result = 31 * result + (paymentMethod != null ? paymentMethod.hashCode() : 0);
        result = 31 * result + (cardAmount != null ? cardAmount.hashCode() : 0);
        result = 31 * result + (cashAmount != null ? cashAmount.hashCode() : 0);
        result = 31 * result + (giftCardDetails != null ? giftCardDetails.hashCode() : 0);
        result = 31 * result + (properties != null ? properties.hashCode() : 0);
        result = 31 * result + (groupPublicId != null ? groupPublicId.hashCode() : 0);
        return result;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
